### ISSUE TITLE
TypeError: Cannot read property 'format' of null

### ISSUE THREAD

**Issue by minovision** [projectsophon/hardhat-diamond-abi#13]
The steps to reproduce the error are:
> 1. clone the repo -> https://github.com/mudgen/diamond-1-hardhat.git
> 2. cd into the dir
> 3. open a terminal and run -> hh run scripts/deploy.js  (works)
> 4. install -> https://www.npmjs.com/package/hardhat-diamond-abi/v/3.0.0
> 5. open a terminal and run -> hh run scripts/deploy.js 

## hardhat.config.js

/* global ethers task */
require('@nomiclabs/hardhat-waffle')
require("hardhat-diamond-abi");

// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task('accounts', 'Prints the list of accounts', async () => {
  const accounts = await ethers.getSigners()

  for (const account of accounts) {
    console.log(account.address)
  }
})

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: '0.8.6',
  settings: {
    optimizer: {
      enabled: true,
      runs: 200
    }
  },
  diamondAbi: {
    // (required) The name of your Diamond ABI
    name: "BestDappEver",
  },
}

**Comment by phated** [comment]
I can't replicate the issue. Though, I see you are using some `hh` command, which doesn't seem to exist with the version of hardhat that is installed for the repo. When I run `./node_modules/.bin/hardhat --version`, I get 2.4.1 but I think you might have an old version installed globally. I'd recommend you don't install hardhat globally and instead use the commands of the hardhat installed by a project.

**Comment by phated** [comment]
Scratch that above. I did `./node_modules/.bin/hardhat compile --force` and see the error

**Comment by phated** [comment]
If you don't configure an `include` or `exclude` array in the configuration, you process literally every contract in the project. That causes the Diamond itself to be processed, which is 100% incorrect. You need to limit the contracts you process to just the Facets.

However, I'll going to add a check for this scenario and throw a better error to tell you what you did wrong.

**Comment by phated** [comment]
I actually don't like throwing for this and we already filter the constructor from the ABI so I will filter `fallback` and `receive` too

**Comment by phated** [comment]
Note, however, that even with the fix, you will still receive an error because the diamond-1-hardhat project has multiple contracts that contain `supportsInterface` which need to be filtered down to 1 instance.

**Comment by minovision** [comment]
resolved, thanks so much for looking into this, much appreciated. I used the following and it worked like a charm.

  diamondAbi: {
    // (required) The name of your Diamond ABI.
    name: "BestDappEver",
    exclude: ["Diamond", "IERC173"],
    strict: true,
  },

**Comment by minovision** [comment]
resolved, thanks so much for looking into this, much appreciated. I used the following and it worked like a charm.

  diamondAbi: {
    // (required) The name of your Diamond ABI.
    name: "BestDappEver",
    exclude: ["Diamond", "IERC173"],
    strict: true,
  },

**Comment by minovision** [comment]
I just got back to working on the diamond and determined that the diamondCut() is not added to the ABI. As a result i can not call the function.
[BestDappEver.txt](https://github.com/projectsophon/hardhat-diamond-abi/files/9048426/BestDappEver.txt)

if i remove Diamond from the exclude it is added however i get duplicates

**Comment by phated** [comment]
The diamond does not provide DiamondCut, the DiamondLoupeFacet does. The strings in your exclude are matched against the contract name, so you are excluding your facets with Diamond* in the name. Use something like `Facet` in your includes instead.
