### ISSUE TITLE
A lot of `duplicate definition` warnings

### ISSUE THREAD

**Issue by liu-zhipeng** [projectsophon/hardhat-diamond-abi#18]
![image](https://user-images.githubusercontent.com/57480598/185998494-e8aba497-38a6-4c81-9950-872e38dbd74d.png)

**Comment by phated** [comment]
Seems like your base contracts have a lot of bad/unnecessary public functions

**Comment by liu-zhipeng** [comment]
`hardhat-diamond-abi` generates a lot of `duplicate definition` warnning while hardhat compiling.

https://github.com/projectsophon/hardhat-diamond-abi/blob/d2099b29a2c7cdb0bed7bd51fd2481d61c46497d/src/index.ts#L257

I tried to compile with `strict: true` config. but it failed because there are duplicated definitions.

Actually there are all from base contract (`BaseConnextFacet`) for all facet contracts.

**Comment by liu-zhipeng** [comment]
> Seems like your base contracts have a lot of bad/unnecessary public functions

They are not public functions. they're custom error definitions.

**Comment by phated** [comment]
>  they're custom error definitions.

You need to specify a `filter` function to limit to 1 definition. Custom Events and Errors can have the same **signature** but **mean** different things across facets. When you are **sure** you know what you are doing, you can filter duplicate Events or Errors using the `filter` option.

**Comment by liu-zhipeng** [comment]
> > they're custom error definitions.
> 
> You need to specify a `filter` function to limit to 1 definition. Custom Events and Errors can have the same **signature** but **mean** different things across facets. When you are **sure** you know what you are doing, you can filter duplicate Events or Errors using the `filter` option.

`filter` conig can't resolve above problem.

https://github.com/projectsophon/hardhat-diamond-abi/blob/d2099b29a2c7cdb0bed7bd51fd2481d61c46497d/src/index.ts#L237

Because filter can be applied to only **function**. My my problem is from the **error**
.

**Comment by liu-zhipeng** [comment]
Yes, `filter` is helpful for filtering some duplicated errors. but it can't resolve current issue completely.

**Comment by phated** [comment]
I've used `filter` to dedupe anything in the ABI, including custom events and errors. If you write your filter correctly, it can solve the issues you have .
