### ISSUE TITLE
Failed to create Diamond ABI - `InitializationFunctionReverted(address,bytes)` appears twice.

### ISSUE THREAD

**Issue by gameblock1** [projectsophon/hardhat-diamond-abi#21]
Hi
I am trying to compile but I get this error:
``Error in plugin hardhat-diamond-abi: Failed to create Diamond ABI - `InitializationFunctionReverted(address,bytes)` appears twice.``
But I searched for that and it is defined only once in the whole project.
I am using [diamond-3-hardhat](https://github.com/mudgen/diamond-3-hardhat)
and this is how I imported modules in hardhat.config.ts:
```
import 'dotenv/config';
import { HardhatUserConfig } from 'hardhat/config';
import 'hardhat-diamond-abi'; // must be imported before typechain

import '@nomicfoundation/hardhat-ethers';
import 'hardhat-deploy';
import 'hardhat-deploy-ethers';
import '@nomicfoundation/hardhat-chai-matchers';

import '@typechain/hardhat';
import 'hardhat-gas-reporter';
//import 'solidity-coverage';
import 'hardhat-contract-sizer';
```

**Comment by phated** [comment]
Use filtering.

**Comment by gameblock1** [comment]
Well `InitializationFunctionReverted(address,bytes)` is not repeated at all. Why am I getting this error?

**Comment by phated** [comment]
Because of literally the only open issue: https://github.com/projectsophon/hardhat-diamond-abi/issues/17
