### ISSUE TITLE
Allow generation of multiple diamond ABIs for a project

### ISSUE THREAD

**Issue by syoon123** [projectsophon/hardhat-diamond-abi#5]
Because `generateDiamondAbi` expects a literal called `diamondAbi` within the Hardhat runtime environment (line 181 of `index.ts`), if one has multiple diamonds within a project, there is no way for one to combine the facets of each diamond into separate ABIs.

**Comment by phated** [comment]
Yeah, I had a similar problem with other HH plugins and submitted PRs to them. I'll look into getting this feature added!

**Comment by friskyfoxdk** [comment]
I'd also love to see this implemented.

**Comment by friskyfoxdk** [comment]
I opened a PR here for some example code I wrote that got this working: https://github.com/projectsophon/hardhat-diamond-abi/pull/9

**Comment by hickscorp** [comment]
I would like to extend this request to something slightly more complicated.
In our project, we deploy new Diamonds regularly - imagine an on-demand deployment platform where new customers get a new diamond.
In this regard, we use a `hardhat task` to help deploying a new diamond programmatically.
It would be really nice to keep this kind of pattern in mind so that the effort put in this issue could also cover for that.

**Comment by hickscorp** [comment]
Any progress on this? Would @friskyfoxdk 's code be merged at any point?

**Comment by phated** [comment]
@hickscorp That PR won't land, as he never applied my changes, and tried to claim the plugin as his own in the fork. I am spending time on this project this week to bring awareness to my gitcoin grant so I can reimplement the change you need.

Can you explain your desire for on-demand automatic deployments and your desired changes for this plugin to make that work?

**Comment by phated** [comment]
I just published v3.0.0 with support for an array of multiple config objects! 🎉 

@hickscorp I hope it fits your use case since I didn't hear back.

**Comment by hickscorp** [comment]
Amazing. I will try today and report back if things don't work the way I would like them to work. Thanks for being so responsive @phated .

**Comment by hickscorp** [comment]
@phated Just a quick update - we're now using `hardhat-diamond-abi` in projects where several diamond ABIs must be consolidated and it works great!
